### ISSUE TITLE
迪粉桌面下边显示导航栏时，运行易控后又多出一个导航栏

### ISSUE THREAD

**Issue by qet006** [eiyooooo/Easycontrol_For_Car#1]
迪粉桌面下边显示导航栏时，运行易控后又多出一个导航栏

**Comment by eiyooooo** [comment]
> 迪粉桌面下边显示导航栏时，运行易控后又多出一个导航栏

迪粉桌面切换一下主题样式再切回去，可能是迪粉桌面作者做了某些更改导致这个原因
