### ISSUE TITLE
应用安装后没有图标

### ISSUE THREAD

**Issue by star-o0O** [eiyooooo/Easycontrol_For_Car#11]
领克03-23版-8155/安卓9车机
由于车机系统限制，无法授予悬浮窗权限，因此之前一直用不了易控车机版
此次更新后已经可以用全屏模式打开，但在使用中发现一个问题：

程序安装后没有图标

在车机桌面中，三方应用图标无法显示在主屏幕，而是出现在类似“抽屉”的地方，然而奇怪的是“抽屉”里也没有易控车机版的图标，导致难以启动程序
经测试，原版易控可以正常显示图标，绝大多数常见应用也可以正常显示
大佬能尝试解决一下么，需要我提供哪些日志

感谢

**Comment by eiyooooo** [comment]
尝试卸载后重启车机再安装，易控车机版是正常的app，和其他app应该是一样的

**Comment by star-o0O** [comment]
> 尝试卸载后重启车机再安装，易控车机版是正常的app，和其他app应该是一样的

试了几次，不行。在手机和平板上都很正常，车机上就是不行T-T

**Comment by eiyooooo** [comment]
下载release里的安装包还是用的GitHub编译？

**Comment by star-o0O** [comment]
> 下载release里的安装包还是用的GitHub编译？

github编译的，刚试了下，换成release里的就可以正常显示了T-T
