### ISSUE TITLE
车机上安装好运行闪退

### ISSUE THREAD

**Issue by juvenman** [eiyooooo/Easycontrol_For_Car#15]
车机的安卓版本是5.1，是不是版本太低的缘故

**Comment by eiyooooo** [comment]
尝试一下这个能否解决，解压后得到安装包

[debug#15.zip](https://github.com/eiyooooo/Easycontrol_For_Car/files/15142026/debug.15.zip) `SHA-256: A7451671893ED9BC8579737628C7EF0DDB6E41E71728D055B8EF8F3847E27521`

**Comment by juvenman** [comment]
感谢大佬，安装新的包不闪退，可以用了。
