### ISSUE TITLE
使用有线连接车机后，易控车机版和百度carlife授权冲突

### ISSUE THREAD

**Issue by simonleeeeee** [eiyooooo/Easycontrol_For_Car#16]
2019比亚迪唐，dlink1.0，可能跟操作系统关系不大，毕竟dlink1.0系统基本没有任何授权限制，不像后来比亚迪的dlink2.0-5.0对开发者权限调用限制越来越多。
我现在遇到的问题是，我一直在用有线百度carlife，我的手机是oppo find n，使用有线连接车机后，之前会自动弹出百度carlife的授权弹窗，安装易控后，易控车机版app和百度carlife都会弹出usb授权的弹窗，只要给易控授权，百度carlife就黑屏了。。。。。。

**Comment by eiyooooo** [comment]
在安卓系统上usb是独占的，一个软件连接成功之后其他软件就不能同时使用usb

可以尝试其中一个无线连接

**Comment by wdubaiyu** [comment]
可以使用wifi连接，那个usb和别的软件冲突很正常。

**Comment by simonleeeeee** [comment]
> 在安卓系统上usb是独占的，一个软件连接成功之后其他软件就不能同时使用usb
> 
> 可以尝试其中一个无线连接

> 可以使用wifi连接，那个usb和别的软件冲突很正常。

我是可以使用wifi连接易控，但是实际用车需求是行使中使用usb连接百度carlife、hicar这一类软件，主要还是有线无延迟。只要把有线连接上车机和手机，车机还是会同时弹出易控车机版、百度carlife的授权提示框。。。。。。如果可以的话能不能让易控车机版可以选择，软件启动后，自动拒绝usb授权或自动允许usb授权，不再弹窗。。。。感谢
