### ISSUE TITLE
可以不等比缩放不

### ISSUE THREAD

**Issue by fanwei001** [eiyooooo/Easycontrol_For_Car#22]
可以不等比缩放不

**Comment by eiyooooo** [comment]
应用流转打开宽高比例自由缩放即可不等比缩放

屏幕镜像考虑到设备分辨率可能难以恢复所以自V1.6.0取消了，有需要可以尝试老版本

**Comment by cjameslynn** [comment]
右下角就可以缩放，不过还是希望做个图示，左下角建议也设置缩放

**Comment by eiyooooo** [comment]
> 右下角就可以缩放，不过还是希望做个图示，左下角建议也设置缩放

使用说明里有图示，缩放检测需要占用画面位置导致下层内容无法点击，故只设计右下角缩放

**Comment by cjameslynn** [comment]
> 应用流转打开宽高比例自由缩放即可不等比缩放
> 
> 屏幕镜像考虑到设备分辨率可能难以恢复所以自V1.6.0取消了，有需要可以尝试老版本

希望可以加回来

**Comment by cjameslynn** [comment]
> 应用流转打开宽高比例自由缩放即可不等比缩放
> 
> 屏幕镜像考虑到设备分辨率可能难以恢复所以自V1.6.0取消了，有需要可以尝试老版本

开启了，应用流转还是不能全屏

**Comment by lvyuanx** [comment]
> 应用流转打开宽高比例自由缩放即可不等比缩放
> 
> 屏幕镜像考虑到设备分辨率可能难以恢复所以自V1.6.0取消了，有需要可以尝试老版本

希望能够增加开关，能够自行选择等比缩放，或者自由推拽，或者允许选择其它比例(如：16:9、18:9)进行推拽，感觉推拽就更加灵活
