### ISSUE TITLE
应用流转只能流转上一个应用，不能选择指定app

### ISSUE THREAD

**Issue by cjameslynn** [eiyooooo/Easycontrol_For_Car#24]
应用流转只能流转上一个应用，不能选择指定app

**Comment by eiyooooo** [comment]
指定app请在设备设置内填写包名，否则自动流转最近使用的应用

**Comment by cjameslynn** [comment]
能否读取一下app列表，然后列到车机上。车机选择app流转

**Comment by eiyooooo** [comment]
> 能否读取一下app列表，然后列到车机上。车机选择app流转
> 

之前有试过，非常不稳定，就改为现在的逻辑

**Comment by cjameslynn** [comment]
手动刷新，不用每次刷新

**Comment by cjameslynn** [comment]
这个问题解决了，直接流转carlife上的车联助手就可以 了
