### ISSUE TITLE
能不能在比亚迪360打开时隐藏，关闭恢复呀

### ISSUE THREAD

**Issue by qet006** [eiyooooo/Easycontrol_For_Car#3]
能不能在比亚迪360打开时隐藏，关闭恢复呀

**Comment by eiyooooo** [comment]
使用tasker或MacroDroid检测某软件是否打开，配合广播可实现，广播使用方法参考[这里](https://github.com/eiyooooo/Easycontrol_For_Car/blob/main/HOW_TO_USE.md)
