### ISSUE TITLE
同时流转多个应用时，点击上一个应用，其图层无法移到最前面

### ISSUE THREAD

**Issue by cjameslynn** [eiyooooo/Easycontrol_For_Car#33]
后面流转的应用会遮挡前一个应用的窗口，
点击前一个应用，并不会使它显示在前方，依然被后一个应用遮挡

**Comment by eiyooooo** [comment]
受限于安卓悬浮窗特性，悬浮窗无法调整自身Z轴层级，若通过软件内部调整层级会出现画面闪烁的情况

若需调整层级可手动最小化再展开
