### ISSUE TITLE
反馈个问题：横竖屏切换后画面显示不全，还有不支持音频传输，日志附在后面

### ISSUE THREAD

**Issue by LiamJiang** [eiyooooo/Easycontrol_For_Car#6]
![mmexport1712409068457](https://github.com/eiyooooo/Easycontrol_For_Car/assets/44234300/6a9fd691-81f5-468b-afc0-1851dfb137f5)
![mmexport1712409070424](https://github.com/eiyooooo/Easycontrol_For_Car/assets/44234300/588653c5-66c2-445f-b01d-f7294b4e9872)
`
PD2232:/ $
app_process -Djava.class.path=/data/local/tmp/easycontrol_for_car_sjava.class.path=/data/local/tmp/easycontrol_for_car_s                         <erver_10411.jar / top.eiyal/tmp/easycontrol_for_car_server_10411.jar / top.eiy                         <ooooo.easycontrol.server.r_server_10411.jar / top.eiyooooo.easycontrol.server.                         <Scrcpy mirrorMode=1
DEBUG: <20:58:40> Try to get method from DisplayControl
DEBUG: <20:58:40> Construct Channel without a context
DEBUG: <20:58:40> Runnable run
DEBUG: <20:58:40> Context: android.app.ContextImpl@e8df84b
DEBUG: <20:58:40> PHONE_INFO->{"Build.MANUFACTURER":"vivo","Build.MODEL":"V2232A","Build.DEVICE":"PD2232","Build.VERSION.RELEASE":"14","Build.VERSION.SDK_INT":34,"Build.BOARD":"taro","Build.PRODUCT":"PD2232","Build.USER":"compiler","Build.BRAND":"vivo","Build.HARDWARE":"qcom","Build.SUPPORTED_ABIS":"[arm64-v8a, armeabi-v7a, armeabi]"}
DEBUG: <20:58:54> onDisplayChanged invoked displayId:0
DEBUG: <20:59:15> Try to get method from DisplayControl
DEBUG: <20:58:54> onDisplayChanged invoked displayId:0
DEBUG: <20:58:55> onDisplayChanged invoked displayId:0
WARN: <20:59:15> Cannot create AudioRecord, try Vivo
WARN: <20:59:15> Audio not supported: : java.lang.RuntimeException: Cannot create AudioRecord
      at top.eiyooooo.easycontrol.server.helper.AudioCapture.createAudioRecordVivo(AudioCapture.java:188)
      at top.eiyooooo.easycontrol.server.helper.AudioCapture.init(AudioCapture.java:34)
      at top.eiyooooo.easycontrol.server.helper.AudioEncode.init(AudioEncode.java:30)
      at top.eiyooooo.easycontrol.server.Scrcpy.main(Scrcpy.java:51)
      at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
      at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:393)

DEBUG: <20:59:15> Android14 method DisplayId: 88

DEBUG: <20:59:15> onDisplayAdded invoked displayId:87
DEBUG: <20:59:15> onDisplayChanged invoked displayId:87
DEBUG: <20:59:15> onDisplayAdded invoked displayId:88
DEBUG: <20:59:15> onDisplayChanged invoked displayId:88

DEBUG: <20:59:17> onDisplayChanged invoked displayId:88

<20:59:20> java.io.IOException: Buffer error
      at d.a.d(SourceFile:1)
      at d.c.f(SourceFile:1)
      at e.i.f(SourceFile:56)
      at e.c.run(SourceFile:28)
      at java.lang.Thread.run(Thread.java:1012)`

**Comment by eiyooooo** [comment]
使用电脑[尝试scrcpy](https://github.com/Genymobile/scrcpy/releases/download/v2.4/scrcpy-win64-v2.4.zip)能否进行音频传输

并将scrcpy命令行的输出信息在此回复一下，谢谢

**Comment by LiamJiang** [comment]
电脑可以音频传输

C:\Users\jiang\Downloads\scrcpy-win64-v2.4\scrcpy-win64-v2.4>scrcpy.exe
scrcpy 2.4 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)  10AD3D18QC001GT                 device  V2232A
C:\Users\jiang\Downloads\scrcpy-win64-v2.4\scrcpy-win64-v2... file pushed, 0 skipped. 76.7 MB/s (69007 bytes in 0.001s)
[server] INFO: Device: [vivo] vivo V2232A (Android 14)
INFO: Renderer: direct3d
INFO: Texture: 1080x2400

**Comment by eiyooooo** [comment]
[app-debug-Android14-audio.zip](https://github.com/eiyooooo/Easycontrol_For_Car/files/14900271/app-debug-Android14-audio.zip)
下载解压得到apk后尝试是否可以音频传输，如果还是不行，日志在此回复一下，谢谢

**Comment by LiamJiang** [comment]
声音没问题了，🐂🍺
